name: nkhani
description: A digital media aggregation platform.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^2.30.0

  # Firebase Authentication
  firebase_auth: ^4.19.0

  # Cloud Firestore
  cloud_firestore: ^4.17.0

  # Firebase Storage
  firebase_storage: ^11.7.0

  # Image Picker
  image_picker: ^1.1.2

  # Image Cropper
  image_cropper: ^11.0.0

  # Image Compression
  flutter_image_compress: ^2.3.0

  # Temporary directories for image processing
  path_provider: ^2.1.5

  # Media
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  share_plus: ^7.2.1
  video_player: ^2.8.2
  chewie: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
